# Generated by Django 6.1 on 2026-08-25 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('branches', '0002_alter_branch_options_branch_created_at_branch_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('connection_type', models.CharField(choices=[('NETWORK', 'Network (IP)'), ('USB', 'USB'), ('BROWSER', 'Browser print dialog (no direct connection)')], default='BROWSER', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('usb_vendor_id', models.CharField(blank=True, max_length=6)),
                ('usb_product_id', models.CharField(blank=True, max_length=6)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PRINTING', 'Printing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='billing.invoice')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='printing.printer')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='printing_pr_status_bf62ff_idx')],
            },
        ),
    ]
