# Generated by Django 6.1 on 2026-08-25 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_created_at_branch_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='ledger_exports/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('RAW_MATERIAL', 'Raw Material'), ('TRANSPORT', 'Transport & Logistics'), ('RENT', 'Rent'), ('SALARY', 'Salary & Wages'), ('UTILITIES', 'Utilities'), ('MARKETING', 'Marketing'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'created_at'], name='ledger_ledg_branch__eefbbc_idx')],
            },
        ),
    ]
