# Generated by Django 6.1 on 2026-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_created_at_branch_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_main_branch',
            field=models.BooleanField(default=False),
        ),
    ]
